### ISSUE TITLE
This plugin genuinely just isn't working at all.

### ISSUE THREAD

**Issue by Droidiar** [SiskSjet/MusicBee-OBS-Tuna#1]
I've tried restarting MusicBee, using a fresh copy of MusicBee, restarting MusicBee and tuna, running obs as admin, reinstalling tuna regularly and from zip, and running MusicBee as admin
and this plugin has not worked.
No error log is generated. I don't know what the problem could be.

**Comment by Droidiar** [comment]
It's sending images but nothing else is being sent other than that I'm pretty sure

**Comment by SiskSjet** [comment]
Sorry for the trouble. When you get at least the cover image, it is a good sign. I'm sure we can resolve it.

Is your music tagged? The plugin reads the tags of the track and sends them to OBS-Tuna.

When OBS and MusicBee are running, check in your Browser [http://localhost:1608/](http://localhost:1608/)
1608 is the default OBS-Tuna port, when changed you have to change it in the URL too. You should get a JSON response with all the information MusicBee has sent to OBS-Tuna.

In OBS-Tuna Settings, did you select Web browser as Music Source?

**Comment by Droidiar** [comment]
You should put on the plugin page and github that you have to put it on web browser. It's working perfectly now

**Comment by SiskSjet** [comment]
It is updated here, but on the plugin page it seems to take a while for the change to become visible
