### ISSUE TITLE
More Supported Tags?

### ISSUE THREAD

**Issue by mimi-min** [SiskSjet/MusicBee-OBS-Tuna#3]
Hello, first of all, thank you for this amazing plug-in! You literally saved my life with this one 😂 

I was just wondering if it’s possible to add more tags to be accessible by Tuna. There are a lot that, when I try to use them, give me a warning that they’re not supported by the source application. Is this a limitation of using Web Browser as a source?

I honestly just need one more space, ideally the comments/description, as I have a command on my stream to pull up the song or artist’s homepage; currently I’m using the “Album” slot instead, but I would prefer to have that spot to be used for… well, the album name.

What would be really cool is if we could somehow set what tag in MusicBee gets sent to which field in Tuna in the configuration options, but I understand that would probably require a lot of work and research. It’s just a thought I had.

I’m also considering reaching out to the developer of Tuna to see if there’s some way we could get native support for MusicBee, with more support for different tags. If anything happens there, I will update here as well.

Thank you!

**Comment by SiskSjet** [comment]
Hi,
what you need might be already supported.
I use something like that in my setup too, but right now, it is hardcoded.
MusicBee has a setting for custom tag and I send custom tag 1 and 2 to OBS-Tuna.
In my MusicBee settings, I have set up custom tag 1 as `Copyright` tag and 2 as `WWW Audio File` tag.
![grafik](https://github.com/user-attachments/assets/fc67ef90-a0c2-4922-9e98-db75bd736cfb)
My music is tagged accordingly. When your music used other tags, you should be able to set up these tags as custom tags in MusicBee and it should work.
|MusicBee|Tuna|
|-|-|
|CustomTag1|Copyright|
|CustomTag2|Url|

OBS-Tuna may print an error when you try to map, for example the URL field, but it will work.

When I created this plugin, I thought about a way to assign tags to tuna, but I thought no one else would tag their music with more information 😄
I will think about it again.

I hope you can archive what you need with the current version.
Please let me know if you need to send more tags to tuna and I'll see what I can do until I find a good way/time to adjust the tag mapping via the settings.

**Comment by mimi-min** [comment]
Oh wow! This is perfect, thank you!

I think custom mapping would be a cool addition, but to be honest I don't think many others would go this far either, so it's probably not super important; more of just a nice thing to have, just in case. 

Either way, I wish you luck! I would offer to help in any way that I can, but I don't think there's much I can do unfortunately 😅
